# Generated by Django 5.0.6 on 2024-05-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('no_media', 'Без медиа'), ('photo', 'Фото'), ('video', 'Видео'), ('document', 'Документ')], help_text='Тип медиа', max_length=50, verbose_name='Тип медиа')),
                ('text', models.TextField(blank=True, help_text='Текст рассылки', max_length=4096, null=True, verbose_name='Текст')),
                ('file_id', models.CharField(blank=True, help_text='File ID медиа рассылки', max_length=255, null=True, verbose_name='File ID')),
                ('date_malling', models.DateTimeField(help_text='Дата рассылки', verbose_name='Дата')),
                ('is_sent', models.BooleanField(default=False, help_text='Статус отправки', verbose_name='Статус отправки')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Прикрепленный файл')),
            ],
            options={
                'verbose_name': 'Рассылки',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
