# Generated by Django 5.0.7 on 2025-01-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mailing',
        ),
    ]
